### ISSUE TITLE
not in Nuget at the moment

### ISSUE THREAD

**Issue by BrannonKing** [pysco68/Pysco68.SignalR.HawkClient#1]
I don't see this HawkClient library in the Nuget Gallery at the moment. Is it gone on purpose?

**Comment by pysco68** [comment]
Well I didn't just have time for that within the last weeks, but I'll probably get to this in the next few days.

**Comment by pysco68** [comment]
Nuget package is now available: see f42284b6dd7cf33f977537a449fbaa822c29a4ac
